default_platform(:android)

# import_from_url(url: 'https://raw.githubusercontent.com/dorukkangal/fastlane-plugin-import_from_url/master/fastlane/FastfileForTest')
import('.cache/DownloadedFastfile')

lane :test do
  hello_world
end
